feat(web): 관리자, 유저에 따른 StoryCard 추가, Dialog 추가
DGSW-Bamboo/bamboo pull request #12
Opened 2021-03-31 05:38 UTC by SoonGwan

2021-03-31 06:20 UTC, HowToBeAHappyBoy requested changes
web-ui가 아니라 ui나 ui-toolkit 같은 app 이름이 괜찮을 듯, admin-web에서도 쓸거라서!

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +  }
이 부분은 useMemo로 처리가능

자바스크립트 할때 생각하면 좋은것 2가지는
1. for, while, switch가 아닌 처리법은 없을지 생각
2. let을 사용하지 않을 방법을 생각

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +        </Box>
다이얼로그가 너무 관리자 입장에서만 설계된게 아닐까?
색이나 메시지는 외부에서 넘어오는게 확장성 있는 설계가 아닐까?

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +      <span />
요 span은 뭘까 ㅋㅋㅋ

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +        </Box>
타입에 의해 색과 메시지가 정해지기 보단, 외부에서 색과 메시지를 넘기도록 하면 좋을듯
context로 감싸고 showDialog 함수를 만들어서 색과 메시지를 넘기는 식으로?

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +          )}
focusRef는 어떤 역할을 하는거야?

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +              onClick={() => setIsRejectOpen(true)}
인라인 함수는 매번 함수가 재생성되기 때문에, 가급적 사용하지 않는게 좋을 것 같아!

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +  }
useMemo로 사용 가능

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +  }
이렇게 하면 매 렌더링마다 할당과 재할당이 일어나서 성능적으로 안좋을 것 같음

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +          )}
props가 다른 두개의 컴포넌트가 공존하는게 좀 찝찝한데, 상태를 하나로 합치고 props를 컨트롤할 방법은 없을까?

2021-03-31 06:20 UTC, HowToBeAHappyBoy commented
StoryCard와 Dialog를 2개의 PR로 나눠줬으면 어땠을까..하는 마음..
200줄이 넘어가면 pr 보기가 빡세다..

2021-03-31 06:22 UTC, HowToBeAHappyBoy commented
storybook 셋팅 해야겠다

2021-03-31 06:33 UTC, HowToBeAHappyBoy commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +}
Props에서만 쓰이는 타입이니까 그냥 Props라는 이름으로 가도될 것 같아
interface와 type은 큰 차이가 없으니까 type을 쓰는건 어떨까? 왜냐면 내가 type을 좋아해...

2021-04-01 05:28 UTC, SoonGwan commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +  }
넵

2021-04-01 05:28 UTC, SoonGwan commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +        </Box>
넵

2021-04-01 05:30 UTC, SoonGwan commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +          )}
focusRef가 클릭후 다시 그 버튼에 포커스 잡아 주는거에요.
근데 필요없을거 같아 삭제했어요

2021-04-01 05:30 UTC, SoonGwan commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +              onClick={() => setIsRejectOpen(true)}
넵

2021-04-01 05:30 UTC, SoonGwan commented on libs/web-ui/src/lib/Dialog/DialogAlert.tsx
> +}
넵

2021-04-02 13:35 UTC, SoonGwan commented on libs/web-ui/src/lib/StoryCard/StoryCard.tsx
> +  }
넵

2021-04-11 06:17 UTC, HowToBeAHappyBoy approved these changes
LGTM 머지되면 리팩토링 한번 할게~

2021-04-11 06:17 UTC, HowToBeAHappyBoy commented
그리고 Master 풀 받을때는 rebase 옵션으로 받자 Merge 커밋 안 생기게~!

2021-04-11 06:26 UTC, SoonGwan commented
넵.. 죄송합니당...

2021-04-11 06:26 UTC, merged